version: '3'
services:
#  nginx:
#    build: ./nginx
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # this is only for development, so we don't have to rebuild image everytime
#    ports:
#      - "8000:80"   # remember the port in browser or client will use is domain:8000 not 80!, the 80 is the mapped container port to this port inside
#    depends_on:
#      - app1    # nginx need access to app1 (nodejs server)
  app1:
    build: ./app
    volumes:
      - ./app/src:/home/app
      - /home/app/node_modules
    restart: always
    ports:
      - "5400:3000"
  # 2 other services we could add later
  #postgres:
  #redis