version: '3'
services:

  db:
    image: postgres:10.5-alpine
	restart: always
	volumes:
		- db_data:/var/lib/postgresql/data    
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secure1
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"

volumes:
	db_data: