version: '3'
services:
  db:
    build: ./postgres
    restart: always
    volumes:
      #- db_data:/var/lib/postgresql/data
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - db.env
# This is being used for storing permamently
volumes:
  dbdata: