# Set nginx base image
FROM nginx:alpine

# File Author / Maintainer
MAINTAINER Your name

# Copy custom configuration file from the current directory
# This is being used when installing in the end production
#COPY nginx.conf /etc/nginx/nginx.conf
